{{- if .Values.ingress.enabled -}}
{{- $fullName := include "netmaker.fullname" . -}}
{{- $fullUIName := printf "%s-%s" $fullName "ui" -}}
{{- $fullRESTName := printf "%s-%s" $fullName "rest" -}}
{{- $fullMQName := printf "%s-%s" $fullName "mqtt" -}}
{{- $uiSvcPort := .Values.service.uiPort -}}
{{- $restSvcPort := .Values.service.restPort -}}
{{- $mqSvcPort := 8883 -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName:  {{ required "A valid .Values.ingress.className entry required!" .Values.ingress.className}}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.ingress.hostPrefix.broker }}.{{ .Values.baseDomain }}"
        - "{{ .Values.ingress.hostPrefix.rest }}.{{ .Values.baseDomain }}"
        - "{{ .Values.ingress.hostPrefix.ui }}.{{ .Values.baseDomain }}"
      secretName: {{ $fullName }}-tls-secret
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostPrefix.broker }}.{{ .Values.baseDomain }}"
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullMQName }}
                port:
                  number: {{ $mqSvcPort }}
              {{- else }}
              serviceName: {{ $fullMQName }}
              servicePort: {{ $mqSvcPort }}
              {{- end }}
    - host: "{{ .Values.ingress.hostPrefix.rest }}.{{ .Values.baseDomain }}"
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullRESTName }}
                port:
                  number: {{ $restSvcPort }}
              {{- else }}
              serviceName: {{ $fullRESTName }}
              servicePort: {{ $restSvcPort }}
              {{- end }}
    - host: "{{ .Values.ingress.hostPrefix.ui }}.{{ .Values.baseDomain }}"
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullUIName }}
                port:
                  number: {{ $uiSvcPort }}
              {{- else }}
              serviceName: {{ $fullUIName }}
              servicePort: {{ $uiSvcPort }}
              {{- end }}
{{- end }}


