apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}-ui
  name: {{ include "netmaker.fullname" . }}-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}-ui
    spec:
      containers:
      - name: {{ include "netmaker.fullname" . }}-ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.ui.resources.requests.memory }}
            cpu: {{ .Values.ui.resources.requests.cpu }}
        ports:
        - containerPort: {{ .Values.service.uiPort }}
        env:
        - name: BACKEND_URL
          {{- if .Values.ingress.enabled }}
          value: "https://{{ .Values.ingress.hostPrefix.rest }}.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}"
          {{- else }}
          value: http://{{ include "netmaker.fullname" . }}-rest.{{ .Release.Namespace }}.svc.cluster.local:8081
          {{- end }}
      terminationGracePeriodSeconds: 15