apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-ui'
spec:
  ports:
  - port: {{ .Values.service.uiPort }}
    protocol: TCP
    targetPort: {{ .Values.service.uiPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}-ui'
  sessionAffinity: None
  type: '{{ .Values.service.type }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-rest'
spec:
  ports:
  - name: rest
    port: {{ .Values.service.restPort }}
    protocol: TCP
    targetPort: {{ .Values.service.restPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
  sessionAffinity: None
  type: {{ .Values.service.type }}

