apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-ui'
spec:
  ports:
  - port: {{ .Values.service.uiPort }}
    protocol: TCP
    targetPort: {{ .Values.service.uiPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}-ui'
  sessionAffinity: None
  type: '{{ .Values.service.type }}'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-rest'
spec:
  ports:
  - name: rest
    port: {{ .Values.service.restPort }}
    protocol: TCP
    targetPort: {{ .Values.service.restPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- if .Values.service.wireguard.healthcheck.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-wg-healthcheck'
spec:
  type: {{ .Values.service.wireguard.healthcheck.serviceType }}
  ports:
  - name: wg-healthcheck
    protocol: TCP
    port: {{ .Values.service.wireguard.healthcheck.port }}
    targetPort: 80
    {{- if .Values.service.wireguard.healthcheck.nodePort }}
    nodePort: {{ .Values.service.wireguard.healthcheck.nodePort }}
    {{- end }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
{{- end }}
